/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.template;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.*;
import java.io.*;

public class AppTest {
    @Test
    public void readResource() throws IOException {
        URL resource = getClass().getClassLoader().getResource("ignoredResources.txt");
        assertNotNull(resource);

        try (
                InputStream is = resource.openStream();
                BufferedReader bufferReader = new BufferedReader(new InputStreamReader(is))) {

            StringBuilder stringBuilder = new StringBuilder();

            String line;

            while ((line = bufferReader.readLine()) != null) {
                stringBuilder.append(line).append("\n");
            }

            String textDataFromFile = stringBuilder.toString().strip();

            assertEquals("HELLO SENG", textDataFromFile);
        }
    }
}
